openid_client:
  auth_redirect_url: https://authtest.mydom.com/oauth2/auth
  token_url: https://authtest.mydom.com/oauth2/token
  response_type: code
  grant_type: authorization_code
  client_id: hardware-native
  redirect_port: 55145 # A socket will be opened in this port and redirect uri will be 'http://localhost:{redirect_port}'
  scope: 'openid offline_access'

browser:
  cmd: firefox # command to launch browser (firefox, chrome, chromium, etc)

output: # values to print from openid server token response
  - access_token
  - refresh_token
  - token_type
  # - id_token